'use client'

import { useState, useEffect } from 'react'
import { useParams, useRouter } from 'next/navigation'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Switch } from '@/components/ui/switch'
import { Textarea } from '@/components/ui/textarea'
import { PasswordInput } from '@/components/ui/password-input'
import Link from 'next/link'
import { ArrowLeft, Save, RefreshCw, Copy, Check, Mail, Edit, Trash2, Plus, Star } from 'lucide-react'

// Generate a secure random password
function generateSecurePassword(): string {
  const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnpqrstuvwxyz23456789!@#$%'
  let password = ''
  for (let i = 0; i < 12; i++) {
    password += chars.charAt(Math.floor(Math.random() * chars.length))
  }
  return password
}

// Generate a URL-safe random slug
function generateRandomSlug(): string {
  const chars = 'abcdefghjkmnpqrstuvwxyz23456789'
  let slug = ''
  // Generate 8-12 character slug
  const length = 8 + Math.floor(Math.random() * 5) // Random length between 8-12
  for (let i = 0; i < length; i++) {
    slug += chars.charAt(Math.floor(Math.random() * chars.length))
    // Add occasional hyphen for readability (but not at start/end)
    if (i > 0 && i < length - 1 && Math.random() < 0.2) {
      slug += '-'
    }
  }
  // Clean up any double hyphens
  return slug.replace(/-+/g, '-')
}

interface Recipient {
  id?: string
  email: string
  name: string | null
  isPrimary: boolean
}

interface Project {
  id: string
  title: string
  slug: string
  description: string | null
  enableRevisions: boolean
  maxRevisions: number
  currentRevision: number
  restrictCommentsToLatestVersion: boolean
  hideFeedback: boolean
  sharePassword: string | null
  sharePasswordDecrypted: string | null
  previewResolution: string
  watermarkEnabled: boolean
  watermarkText: string | null
}

export default function ProjectSettingsPage() {
  const params = useParams()
  const router = useRouter()
  const projectId = params?.id as string

  const [project, setProject] = useState<Project | null>(null)
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState('')
  const [success, setSuccess] = useState(false)
  const [copiedPassword, setCopiedPassword] = useState(false)

  // Form state
  const [title, setTitle] = useState('')
  const [description, setDescription] = useState('')
  const [enableRevisions, setEnableRevisions] = useState(false)
  const [maxRevisions, setMaxRevisions] = useState<number | ''>('')
  const [currentRevision, setCurrentRevision] = useState<number | ''>('')
  const [restrictCommentsToLatestVersion, setRestrictCommentsToLatestVersion] = useState(false)
  const [hideFeedback, setHideFeedback] = useState(false)
  const [sharePassword, setSharePassword] = useState('')
  const [useCustomSlug, setUseCustomSlug] = useState(false) // Toggle for custom slug
  const [customSlugValue, setCustomSlugValue] = useState('') // Store custom slug value
  const [previewResolution, setPreviewResolution] = useState('720p')
  const [watermarkEnabled, setWatermarkEnabled] = useState(true)
  const [watermarkText, setWatermarkText] = useState('')
  const [useCustomWatermark, setUseCustomWatermark] = useState(false)

  // Recipients state
  const [recipients, setRecipients] = useState<Recipient[]>([])
  const [recipientsLoading, setRecipientsLoading] = useState(false)
  const [newRecipientEmail, setNewRecipientEmail] = useState('')
  const [newRecipientName, setNewRecipientName] = useState('')
  const [showAddRecipient, setShowAddRecipient] = useState(false)
  const [editingRecipientId, setEditingRecipientId] = useState<string | null>(null)
  const [editRecipientEmail, setEditRecipientEmail] = useState('')
  const [editRecipientName, setEditRecipientName] = useState('')

  // Track original processing settings for change detection
  const [originalSettings, setOriginalSettings] = useState({
    title: '',
    previewResolution: '720p',
    watermarkEnabled: true,
    watermarkText: null as string | null,
  })

  // Reprocessing state
  const [showReprocessModal, setShowReprocessModal] = useState(false)
  const [pendingUpdates, setPendingUpdates] = useState<any>(null)
  const [reprocessing, setReprocessing] = useState(false)

  // Auto-generate slug from title
  const autoGeneratedSlug = title
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9-]/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')

  // Use custom slug if enabled, otherwise use auto-generated
  const slug = useCustomSlug ? customSlugValue : autoGeneratedSlug

  // Sanitize slug for live preview
  const sanitizedSlug = slug
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9-]/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')

  const copyPassword = async () => {
    if (sharePassword) {
      await navigator.clipboard.writeText(sharePassword)
      setCopiedPassword(true)
      setTimeout(() => setCopiedPassword(false), 2000)
    }
  }

  // Load recipients
  const loadRecipients = async () => {
    setRecipientsLoading(true)
    try {
      const response = await fetch(`/api/projects/${projectId}/recipients`)
      if (response.ok) {
        const data = await response.json()
        setRecipients(data.recipients || [])
      }
    } catch (error) {
      console.error('Failed to load recipients:', error)
    } finally {
      setRecipientsLoading(false)
    }
  }

  // Add recipient
  const addRecipient = async () => {
    if (!newRecipientEmail || !newRecipientEmail.includes('@')) {
      setError('Please enter a valid email address')
      return
    }

    try {
      const response = await fetch(`/api/projects/${projectId}/recipients`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          email: newRecipientEmail,
          name: newRecipientName || null,
          isPrimary: recipients.length === 0, // First recipient is primary
        }),
      })

      if (response.ok) {
        setNewRecipientEmail('')
        setNewRecipientName('')
        setShowAddRecipient(false)
        await loadRecipients()
      } else {
        const data = await response.json()
        setError(data.error || 'Failed to add recipient')
      }
    } catch (error) {
      setError('Failed to add recipient')
    }
  }

  // Delete recipient
  const deleteRecipient = async (recipientId: string) => {
    if (!confirm('Are you sure you want to remove this recipient?')) {
      return
    }

    try {
      const response = await fetch(`/api/projects/${projectId}/recipients/${recipientId}`, {
        method: 'DELETE',
      })

      if (response.ok) {
        await loadRecipients()
      } else {
        const data = await response.json()
        setError(data.error || 'Failed to delete recipient')
      }
    } catch (error) {
      setError('Failed to delete recipient')
    }
  }

  // Set primary recipient
  const setPrimaryRecipient = async (recipientId: string) => {
    try {
      const response = await fetch(`/api/projects/${projectId}/recipients/${recipientId}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ isPrimary: true }),
      })

      if (response.ok) {
        await loadRecipients()
      } else {
        setError('Failed to set primary recipient')
      }
    } catch (error) {
      setError('Failed to set primary recipient')
    }
  }

  // Start editing recipient
  const startEditRecipient = (recipient: Recipient) => {
    setEditingRecipientId(recipient.id!)
    setEditRecipientEmail(recipient.email)
    setEditRecipientName(recipient.name || '')
  }

  // Cancel editing
  const cancelEditRecipient = () => {
    setEditingRecipientId(null)
    setEditRecipientEmail('')
    setEditRecipientName('')
  }

  // Save edited recipient
  const saveEditRecipient = async () => {
    if (!editRecipientEmail || !editRecipientEmail.includes('@')) {
      setError('Please enter a valid email address')
      return
    }

    try {
      const response = await fetch(`/api/projects/${projectId}/recipients/${editingRecipientId}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ name: editRecipientName || null }),
      })

      if (response.ok) {
        await loadRecipients()
        cancelEditRecipient()
      } else {
        const data = await response.json()
        setError(data.error || 'Failed to update recipient')
      }
    } catch (error) {
      setError('Failed to update recipient')
    }
  }

  useEffect(() => {
    async function loadProject() {
      try {
        const response = await fetch(`/api/projects/${projectId}`)
        if (!response.ok) {
          throw new Error('Failed to load project')
        }
        const data = await response.json()
        setProject(data)

        // Set form values
        setTitle(data.title)
        setDescription(data.description || '')
        setEnableRevisions(data.enableRevisions)
        setMaxRevisions(data.maxRevisions)
        setCurrentRevision(data.currentRevision)
        setRestrictCommentsToLatestVersion(data.restrictCommentsToLatestVersion)
        setHideFeedback(data.hideFeedback || false)
        setPreviewResolution(data.previewResolution)
        setWatermarkEnabled(data.watermarkEnabled ?? true)
        setWatermarkText(data.watermarkText || '')
        setUseCustomWatermark(!!data.watermarkText)
        setSharePassword(data.sharePasswordDecrypted || '')

        // Store original processing settings
        setOriginalSettings({
          title: data.title,
          previewResolution: data.previewResolution,
          watermarkEnabled: data.watermarkEnabled ?? true,
          watermarkText: data.watermarkText,
        })

        // Check if slug was manually customized (different from auto-generated from title)
        const autoGeneratedSlug = data.title
          .toLowerCase()
          .trim()
          .replace(/[^a-z0-9-]/g, '-')
          .replace(/-+/g, '-')
          .replace(/^-|-$/g, '')
        
        if (data.slug !== autoGeneratedSlug) {
          setUseCustomSlug(true)
          setCustomSlugValue(data.slug)
        }
      } catch (err) {
        setError('Failed to load project settings')
      } finally {
        setLoading(false)
      }
    }

    loadProject()
    loadRecipients()
  }, [projectId])

  async function handleSave() {
    setSaving(true)
    setError('')
    setSuccess(false)

    try {
      // Sanitize slug: lowercase, replace spaces/special chars with hyphens
      const sanitizedSlug = slug
        .toLowerCase()
        .trim()
        .replace(/[^a-z0-9-]/g, '-')
        .replace(/-+/g, '-')
        .replace(/^-|-$/g, '')

      if (!sanitizedSlug) {
        setError('Share link cannot be empty')
        setSaving(false)
        return
      }

      // Ensure revision values are valid numbers before saving
      const finalMaxRevisions = typeof maxRevisions === 'number' ? maxRevisions : parseInt(String(maxRevisions)) || 1
      const finalCurrentRevision = typeof currentRevision === 'number' ? currentRevision : parseInt(String(currentRevision)) || 0

      // Validate: maxRevisions must be at least 1, currentRevision at least 0
      if (enableRevisions && finalMaxRevisions < 1) {
        setError('Maximum revisions must be at least 1')
        setSaving(false)
        return
      }

      if (enableRevisions && finalCurrentRevision < 0) {
        setError('Current revision count cannot be negative')
        setSaving(false)
        return
      }

      const updates: any = {
        title,
        slug: sanitizedSlug,
        description: description || null,
        enableRevisions,
        maxRevisions: enableRevisions ? finalMaxRevisions : 0,
        currentRevision: enableRevisions ? finalCurrentRevision : 0,
        restrictCommentsToLatestVersion,
        hideFeedback,
        previewResolution,
        watermarkEnabled,
        watermarkText: useCustomWatermark ? watermarkText : null,
        sharePassword: sharePassword || null,
      }

      // Detect changes to processing settings
      const currentWatermarkText = useCustomWatermark ? watermarkText : null
      const processingSettingsChanged =
        title !== originalSettings.title ||
        previewResolution !== originalSettings.previewResolution ||
        watermarkEnabled !== originalSettings.watermarkEnabled ||
        currentWatermarkText !== originalSettings.watermarkText

      // If processing settings changed, show modal
      if (processingSettingsChanged) {
        setPendingUpdates(updates)
        setShowReprocessModal(true)
        setSaving(false)
        return
      }

      // Otherwise save normally
      await saveSettings(updates)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to save settings')
      setSaving(false)
    }
  }

  async function saveSettings(updates: any, shouldReprocess = false) {
    setSaving(true)
    setError('')

    try {
      const response = await fetch(`/api/projects/${projectId}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(updates),
      })

      if (!response.ok) {
        const data = await response.json()
        throw new Error(data.error || 'Failed to save settings')
      }

      // Update custom slug value to sanitized version if using custom slug
      const sanitizedSlug = updates.slug
      if (useCustomSlug) {
        setCustomSlugValue(sanitizedSlug)
      }

      // Reprocess videos if requested
      if (shouldReprocess) {
        await reprocessVideos()
      }

      setSuccess(true)
      setTimeout(() => setSuccess(false), 3000)

      // Reload project data to reflect changes
      const refreshResponse = await fetch(`/api/projects/${projectId}`)
      if (refreshResponse.ok) {
        const refreshedData = await refreshResponse.json()
        setProject(refreshedData)
        setWatermarkEnabled(refreshedData.watermarkEnabled ?? true)
        setWatermarkText(refreshedData.watermarkText || '')
        setUseCustomWatermark(!!refreshedData.watermarkText)

        // Update original settings
        setOriginalSettings({
          title: refreshedData.title,
          previewResolution: refreshedData.previewResolution,
          watermarkEnabled: refreshedData.watermarkEnabled ?? true,
          watermarkText: refreshedData.watermarkText,
        })
      }

      // Refresh the page
      router.refresh()

      // Close modal and reset pending updates
      setShowReprocessModal(false)
      setPendingUpdates(null)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to save settings')
    } finally {
      setSaving(false)
    }
  }

  async function reprocessVideos() {
    setReprocessing(true)
    try {
      const response = await fetch(`/api/projects/${projectId}/reprocess`, {
        method: 'POST',
      })

      if (!response.ok) {
        const data = await response.json()
        throw new Error(data.error || 'Failed to reprocess videos')
      }

      const data = await response.json()
      console.log(`Reprocessing ${data.count} videos`)
    } catch (err) {
      console.error('Error reprocessing videos:', err)
      // Don't throw - we still want to save settings
    } finally {
      setReprocessing(false)
    }
  }

  if (loading) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <p className="text-muted-foreground">Loading...</p>
      </div>
    )
  }

  if (!project) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <p className="text-muted-foreground">Project not found</p>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-4 sm:py-8">
        <div className="mb-4 sm:mb-6">
          <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
            <div className="flex flex-col sm:flex-row sm:items-center gap-3 sm:gap-4">
              <Link href={`/admin/projects/${projectId}`}>
                <Button variant="ghost" size="default">
                  <ArrowLeft className="w-4 h-4 mr-2" />
                  <span className="hidden sm:inline">Back to Project</span>
                  <span className="sm:hidden">Back</span>
                </Button>
              </Link>
              <div className="min-w-0">
                <h1 className="text-2xl sm:text-3xl font-bold">Project Settings</h1>
                <p className="text-sm sm:text-base text-muted-foreground mt-1 truncate">{project.title}</p>
              </div>
            </div>

            <Button onClick={handleSave} variant="default" disabled={saving} size="lg" className="w-full sm:w-auto">
              <Save className="w-4 h-4 mr-2" />
              {saving ? 'Saving...' : 'Save Changes'}
            </Button>
          </div>
        </div>

        {error && (
          <div className="mb-4 sm:mb-6 p-3 sm:p-4 bg-destructive-visible border-2 border-destructive-visible rounded-lg">
            <p className="text-xs sm:text-sm text-destructive font-medium">{error}</p>
          </div>
        )}

        {success && (
          <div className="mb-4 sm:mb-6 p-3 sm:p-4 bg-success-visible border-2 border-success-visible rounded-lg">
            <p className="text-xs sm:text-sm text-success font-medium">Settings saved successfully!</p>
          </div>
        )}

        <div className="space-y-4 sm:space-y-6">
          {/* Project Details */}
          <Card>
            <CardHeader>
              <CardTitle>Project Details</CardTitle>
              <CardDescription>
                Basic project information and client details
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="title">Project Title</Label>
                <Input
                  id="title"
                  type="text"
                  value={title}
                  onChange={(e) => setTitle(e.target.value)}
                  placeholder="e.g., Brand Video Project"
                />
                <p className="text-xs text-muted-foreground">
                  The name of this project as shown to clients and in the admin panel
                </p>
              </div>

              <div className="space-y-2">
                <Label htmlFor="description">Project Description</Label>
                <Textarea
                  id="description"
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  placeholder="e.g., Marketing video for Q4 campaign"
                  rows={3}
                />
                <p className="text-xs text-muted-foreground">
                  Optional description to help identify and organize this project
                </p>
              </div>

              <div className="space-y-4">
                <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2">
                  <div className="space-y-0.5 flex-1">
                    <Label htmlFor="useCustomSlug">Custom Link</Label>
                    <p className="text-xs text-muted-foreground">
                      Use a custom share link instead of auto-generated from project title
                    </p>
                  </div>
                  <Switch
                    id="useCustomSlug"
                    checked={useCustomSlug}
                    onCheckedChange={setUseCustomSlug}
                  />
                </div>

                <div className="space-y-2">
                  <Label htmlFor="slug">Share Link</Label>
                  <div className="flex gap-2 items-center">
                    <span className="text-xs sm:text-sm text-muted-foreground whitespace-nowrap">
                      /share/
                    </span>
                    {useCustomSlug ? (
                      <>
                        <Input
                          id="slug"
                          type="text"
                          value={customSlugValue}
                          onChange={(e) => setCustomSlugValue(e.target.value)}
                          placeholder="e.g., custom-link-name"
                          className="flex-1"
                        />
                        <Button
                          type="button"
                          variant="outline"
                          size="sm"
                          onClick={() => setCustomSlugValue(generateRandomSlug())}
                          title="Generate random URL"
                        >
                          <RefreshCw className="w-4 h-4" />
                        </Button>
                      </>
                    ) : (
                      <Input
                        id="slug"
                        type="text"
                        value={autoGeneratedSlug}
                        disabled
                        className="flex-1 opacity-60"
                      />
                    )}
                  </div>
                  {useCustomSlug && customSlugValue && customSlugValue !== sanitizedSlug && (
                    <p className="text-xs text-warning">
                      Will be saved as: <span className="font-mono font-semibold">{sanitizedSlug}</span>
                    </p>
                  )}
                  <p className="text-xs text-muted-foreground">
                    {useCustomSlug
                      ? 'Custom share link. Only lowercase letters, numbers, and hyphens allowed.'
                      : 'Auto-generated from project title. Enable "Custom Link" to set your own.'}
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Email & Notifications */}
          <Card>
            <CardHeader>
              <CardTitle>Email & Notifications</CardTitle>
              <CardDescription>
                Manage recipients and email notification settings
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              {/* Email Recipients */}
              <div className="space-y-3">
                <div className="flex items-center justify-between">
                  <div>
                    <Label>Recipients</Label>
                    <p className="text-xs text-muted-foreground mt-1">
                      Manage who receives project notifications and updates
                    </p>
                  </div>
                  <Button
                    type="button"
                    variant="default"
                    size="sm"
                    onClick={() => setShowAddRecipient(true)}
                    disabled={showAddRecipient}
                  >
                    <Plus className="w-4 h-4 mr-2" />
                    Add Recipient
                  </Button>
                </div>

                {recipientsLoading ? (
                  <div className="text-sm text-muted-foreground py-4 text-center">
                    Loading recipients...
                  </div>
                ) : recipients.length === 0 && !showAddRecipient ? (
                  <div className="text-sm text-muted-foreground py-4 text-center border border-dashed rounded-lg">
                    No recipients added yet. Click "Add Recipient" to add one.
                  </div>
                ) : (
                  <div className="space-y-2">
                    {recipients.map((recipient) => (
                      <div
                        key={recipient.id}
                        className="border rounded-lg bg-card"
                      >
                        {editingRecipientId === recipient.id ? (
                          // Edit mode
                          <div className="p-4 space-y-3">
                            <div className="space-y-2">
                              <Label htmlFor={`edit-email-${recipient.id}`}>Email Address *</Label>
                              <Input
                                id={`edit-email-${recipient.id}`}
                                type="email"
                                value={editRecipientEmail}
                                onChange={(e) => setEditRecipientEmail(e.target.value)}
                                placeholder="email@example.com"
                                disabled
                                className="opacity-60"
                              />
                              <p className="text-xs text-muted-foreground">Email cannot be changed (delete and re-add to change)</p>
                            </div>
                            <div className="space-y-2">
                              <Label htmlFor={`edit-name-${recipient.id}`}>Name (Optional)</Label>
                              <Input
                                id={`edit-name-${recipient.id}`}
                                type="text"
                                value={editRecipientName}
                                onChange={(e) => setEditRecipientName(e.target.value)}
                                placeholder="John Doe or Company Name"
                                autoFocus
                              />
                            </div>
                            <div className="flex gap-2">
                              <Button
                                type="button"
                                onClick={saveEditRecipient}
                                size="sm"
                              >
                                <Check className="w-4 h-4 mr-2" />
                                Save
                              </Button>
                              <Button
                                type="button"
                                variant="outline"
                                size="sm"
                                onClick={cancelEditRecipient}
                              >
                                Cancel
                              </Button>
                            </div>
                          </div>
                        ) : (
                          // Display mode
                          <div className="flex flex-col sm:flex-row sm:items-center gap-2 p-3">
                            <div className="flex-1 space-y-1 min-w-0">
                              <div className="flex items-center gap-2">
                                <Mail className="w-4 h-4 text-muted-foreground flex-shrink-0" />
                                <span className="text-sm font-medium truncate">{recipient.email}</span>
                                {recipient.isPrimary && (
                                  <span className="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-primary/10 text-primary">
                                    <Star className="w-3 h-3 mr-1" />
                                    Primary
                                  </span>
                                )}
                              </div>
                              {recipient.name && (
                                <div className="flex items-center gap-2 pl-6">
                                  <span className="text-xs text-muted-foreground truncate">{recipient.name}</span>
                                </div>
                              )}
                            </div>
                            <div className="flex items-center gap-2 sm:ml-auto">
                              {!recipient.isPrimary && (
                                <Button
                                  type="button"
                                  variant="ghost"
                                  size="sm"
                                  onClick={() => setPrimaryRecipient(recipient.id!)}
                                  title="Set as primary"
                                >
                                  <Star className="w-4 h-4" />
                                </Button>
                              )}
                              <Button
                                type="button"
                                variant="outline"
                                size="sm"
                                onClick={() => startEditRecipient(recipient)}
                                title="Edit recipient"
                              >
                                <Edit className="w-4 h-4" />
                              </Button>
                              <Button
                                type="button"
                                variant="ghost"
                                size="sm"
                                onClick={() => deleteRecipient(recipient.id!)}
                                title="Remove recipient"
                                className="text-destructive hover:text-destructive"
                              >
                                <Trash2 className="w-4 h-4" />
                              </Button>
                            </div>
                          </div>
                        )}
                      </div>
                    ))}

                    {showAddRecipient && (
                      <div className="p-4 border-2 border-dashed rounded-lg space-y-3">
                        <div className="space-y-2">
                          <Label htmlFor="newRecipientEmail">Email Address *</Label>
                          <Input
                            id="newRecipientEmail"
                            type="email"
                            value={newRecipientEmail}
                            onChange={(e) => setNewRecipientEmail(e.target.value)}
                            placeholder="email@example.com"
                            autoFocus
                          />
                        </div>
                        <div className="space-y-2">
                          <Label htmlFor="newRecipientName">Name (Optional)</Label>
                          <Input
                            id="newRecipientName"
                            type="text"
                            value={newRecipientName}
                            onChange={(e) => setNewRecipientName(e.target.value)}
                            placeholder="John Doe or Company Name"
                          />
                        </div>
                        <div className="flex gap-2">
                          <Button
                            type="button"
                            onClick={addRecipient}
                            size="sm"
                            disabled={!newRecipientEmail}
                          >
                            <Plus className="w-4 h-4 mr-2" />
                            Add
                          </Button>
                          <Button
                            type="button"
                            variant="outline"
                            size="sm"
                            onClick={() => {
                              setShowAddRecipient(false)
                              setNewRecipientEmail('')
                              setNewRecipientName('')
                            }}
                          >
                            Cancel
                          </Button>
                        </div>
                      </div>
                    )}
                  </div>
                )}
              </div>
            </CardContent>
          </Card>

          {/* Video Processing Settings */}
          <Card>
            <CardHeader>
              <CardTitle>Video Processing</CardTitle>
              <CardDescription>
                Configure how videos are processed and displayed
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              {/* Preview Resolution */}
              <div className="space-y-2">
                <Label htmlFor="resolution">Preview Resolution</Label>
                <select
                  id="resolution"
                  value={previewResolution}
                  onChange={(e) => setPreviewResolution(e.target.value)}
                  className="w-full px-3 py-2 bg-card border border-border rounded-md"
                >
                  <option value="720p">720p (1280x720 or 720x1280 for vertical)</option>
                  <option value="1080p">1080p (1920x1080 or 1080x1920 for vertical)</option>
                </select>
                <p className="text-xs text-muted-foreground">
                  Higher resolutions take longer to process and use more storage.
                  Vertical videos automatically adjust dimensions while maintaining aspect ratio.
                </p>
              </div>

              {/* Watermark Enable/Disable */}
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <div className="space-y-0.5">
                    <Label htmlFor="watermarkEnabled">Enable Watermarks</Label>
                    <p className="text-xs text-muted-foreground">
                      Add watermarks to processed videos
                    </p>
                  </div>
                  <Switch
                    id="watermarkEnabled"
                    checked={watermarkEnabled}
                    onCheckedChange={setWatermarkEnabled}
                  />
                </div>

                {watermarkEnabled && (
                  <>
                    <div className="flex items-center justify-between">
                      <div className="space-y-0.5">
                        <Label htmlFor="customWatermark">Custom Watermark Text</Label>
                        <p className="text-xs text-muted-foreground">
                          Override default watermark format
                        </p>
                      </div>
                      <Switch
                        id="customWatermark"
                        checked={useCustomWatermark}
                        onCheckedChange={setUseCustomWatermark}
                      />
                    </div>

                    {useCustomWatermark && (
                      <div className="space-y-2">
                        <Input
                          value={watermarkText}
                          onChange={(e) => setWatermarkText(e.target.value)}
                          placeholder="e.g., CONFIDENTIAL, DRAFT, REVIEW COPY"
                          className="font-mono"
                          maxLength={100}
                        />
                        <p className="text-xs text-muted-foreground">
                          Leave empty to use default format: PREVIEW-{project?.title}-[version]
                          <br />
                          <span className="text-warning">Only letters, numbers, spaces, and these characters: - _ . ( )</span>
                        </p>
                      </div>
                    )}
                  </>
                )}
              </div>
            </CardContent>
          </Card>

          {/* Revision Settings */}
          <Card>
            <CardHeader>
              <CardTitle>Revision Tracking</CardTitle>
              <CardDescription>
                Manage how video revisions are tracked and limited
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2">
                <div className="space-y-0.5 flex-1">
                  <Label htmlFor="enableRevisions">Enable Revision Tracking</Label>
                  <p className="text-xs text-muted-foreground">
                    Track and limit the number of video revisions
                  </p>
                </div>
                <Switch
                  id="enableRevisions"
                  checked={enableRevisions}
                  onCheckedChange={setEnableRevisions}
                />
              </div>

              {enableRevisions && (
                <div className="space-y-4">
                  <div className="space-y-2">
                    <Label htmlFor="maxRevisions">Maximum Revisions</Label>
                    <Input
                      id="maxRevisions"
                      type="number"
                      min="1"
                      max="20"
                      value={maxRevisions}
                      onChange={(e) => {
                        const val = e.target.value
                        if (val === '') {
                          setMaxRevisions('')
                        } else {
                          const num = parseInt(val)
                          if (!isNaN(num)) setMaxRevisions(num)
                        }
                      }}
                      onBlur={(e) => {
                        // Only validate on blur - ensure at least 1
                        const val = e.target.value
                        if (val === '') {
                          setMaxRevisions(1)
                        } else {
                          const num = parseInt(val)
                          if (isNaN(num) || num < 1) setMaxRevisions(1)
                          else if (num > 20) setMaxRevisions(20)
                        }
                      }}
                    />
                    <p className="text-xs text-muted-foreground">
                      Must be at least 1. First upload doesn't count as a revision.
                    </p>
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="currentRevision">Current Revision Count</Label>
                    <Input
                      id="currentRevision"
                      type="number"
                      min="0"
                      max={typeof maxRevisions === 'number' ? maxRevisions : undefined}
                      value={currentRevision}
                      onChange={(e) => {
                        const val = e.target.value
                        if (val === '') {
                          setCurrentRevision('')
                        } else {
                          const num = parseInt(val)
                          if (!isNaN(num)) setCurrentRevision(num)
                        }
                      }}
                      onBlur={(e) => {
                        // Only validate on blur - ensure at least 0
                        const val = e.target.value
                        if (val === '') {
                          setCurrentRevision(0)
                        } else {
                          const num = parseInt(val)
                          const max = typeof maxRevisions === 'number' ? maxRevisions : 20
                          if (isNaN(num) || num < 0) setCurrentRevision(0)
                          else if (num > max) setCurrentRevision(max)
                        }
                      }}
                    />
                    <p className="text-xs text-muted-foreground">
                      Must be at least 0 (0 = initial upload, 1 = first revision, etc.)
                    </p>
                  </div>
                </div>
              )}
            </CardContent>
          </Card>

          {/* Comment Settings */}
          <Card>
            <CardHeader>
              <CardTitle>Feedback & Comments</CardTitle>
              <CardDescription>
                Control how clients can leave feedback
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2">
                <div className="space-y-0.5 flex-1">
                  <Label htmlFor="hideFeedback">Hide Feedback Section</Label>
                  <p className="text-xs text-muted-foreground">
                    Completely hide the feedback and discussion window from clients
                  </p>
                </div>
                <Switch
                  id="hideFeedback"
                  checked={hideFeedback}
                  onCheckedChange={setHideFeedback}
                />
              </div>

              <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2">
                <div className="space-y-0.5 flex-1">
                  <Label htmlFor="restrictComments">Restrict Comments to Latest Version</Label>
                  <p className="text-xs text-muted-foreground">
                    Only allow feedback on the most recent video version
                  </p>
                </div>
                <Switch
                  id="restrictComments"
                  checked={restrictCommentsToLatestVersion}
                  onCheckedChange={setRestrictCommentsToLatestVersion}
                />
              </div>
            </CardContent>
          </Card>

          {/* Security Settings */}
          <Card>
            <CardHeader>
              <CardTitle>Security</CardTitle>
              <CardDescription>
                Password protection for the share page
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="password">Share Page Password</Label>
                <div className="flex gap-2 w-full">
                  <PasswordInput
                    id="password"
                    value={sharePassword}
                    onChange={(e) => setSharePassword(e.target.value)}
                    placeholder="Leave empty to disable password protection"
                    className="flex-1"
                  />
                  <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    onClick={() => setSharePassword(generateSecurePassword())}
                    title="Generate random password"
                    className="h-10 w-10 p-0 flex-shrink-0"
                  >
                    <RefreshCw className="w-4 h-4" />
                  </Button>
                  {sharePassword && (
                    <Button
                      type="button"
                      variant="outline"
                      size="sm"
                      onClick={copyPassword}
                      title={copiedPassword ? 'Copied!' : 'Copy password'}
                      className="h-10 w-10 p-0 flex-shrink-0"
                    >
                      {copiedPassword ? (
                        <Check className="w-4 h-4 text-green-500" />
                      ) : (
                        <Copy className="w-4 h-4" />
                      )}
                    </Button>
                  )}
                </div>
                <p className="text-xs text-muted-foreground">
                  {sharePassword
                    ? 'Password will be required to access the share page'
                    : 'Leave empty to allow anyone with the link to access'}
                </p>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Save button at bottom */}
        <div className="mt-6 sm:mt-8 flex justify-end">
          <Button onClick={handleSave} variant="default" disabled={saving} size="lg" className="w-full sm:w-auto">
            <Save className="w-4 h-4 mr-2" />
            {saving ? 'Saving...' : 'Save All Changes'}
          </Button>
        </div>

        {/* Reprocess Confirmation Modal */}
        {showReprocessModal && (
          <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
            <div className="bg-card border border-border rounded-lg max-w-lg w-full p-6 space-y-4">
              <div className="flex items-start gap-3">
                <div className="text-warning text-2xl">⚠️</div>
                <div className="flex-1">
                  <h2 className="text-xl font-bold">Video Processing Settings Changed</h2>
                  <p className="text-sm text-muted-foreground mt-2">
                    You've changed settings that affect how videos are processed. These changes will only apply to newly uploaded videos.
                  </p>
                </div>
              </div>

              <div className="bg-muted/30 border border-border rounded-lg p-4 space-y-2 text-sm">
                <p className="font-semibold">Would you like to reprocess existing videos?</p>
                <ul className="space-y-1 ml-4 list-disc text-muted-foreground">
                  <li>All existing videos will be regenerated with new settings</li>
                  <li>Old preview files will be deleted (originals are kept safe)</li>
                  <li>Videos will be temporarily unavailable during processing</li>
                  <li>This uses server CPU and storage resources</li>
                </ul>
              </div>

              <div className="flex flex-col sm:flex-row gap-3 pt-2">
                <Button
                  variant="outline"
                  onClick={() => {
                    setShowReprocessModal(false)
                    setPendingUpdates(null)
                    setSaving(false)
                  }}
                  className="flex-1"
                  disabled={saving || reprocessing}
                >
                  Cancel
                </Button>
                <Button
                  variant="outline"
                  onClick={() => saveSettings(pendingUpdates, false)}
                  className="flex-1"
                  disabled={saving || reprocessing}
                >
                  {saving ? 'Saving...' : 'Save Without Reprocessing'}
                </Button>
                <Button
                  variant="default"
                  onClick={() => saveSettings(pendingUpdates, true)}
                  className="flex-1"
                  disabled={saving || reprocessing}
                >
                  {reprocessing ? 'Reprocessing...' : 'Save & Reprocess'}
                </Button>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}
