-- AlterTable
ALTER TABLE "SalesSettings" ADD COLUMN IF NOT EXISTS "quoteLabel" TEXT NOT NULL DEFAULT 'QUOTE';
ALTER TABLE "SalesSettings" ADD COLUMN IF NOT EXISTS "invoiceLabel" TEXT NOT NULL DEFAULT 'INVOICE';
ALTER TABLE "SalesSettings" ADD COLUMN IF NOT EXISTS "taxLabel" TEXT NOT NULL DEFAULT '';
ALTER TABLE "SalesSettings" ADD COLUMN IF NOT EXISTS "taxEnabled" BOOLEAN NOT NULL DEFAULT true;
